### PR TITLE
add patch for 1.8.1 compatibility

### PR DESCRIPTION
**Pull request by deanxorr**
This adds compatibility for 1.8.1-enterprise, which lacks the `CouchAPIBase` node attribute.

The server info JSON for couchbase 1.8.1 includes node information, formatted like this:
```
$ curl http://localhost:21214/pools/default/bucketsStreaming/default
{
  "name":"default",
  "bucketType":"membase",
  ...snip
  "nodes":[{
    "replication":1.0,
    "clusterMembership":"active",
    "status":"healthy",
    "hostname":"127.0.0.1:8091",
    "clusterCompatibility":1,
    "version":"1.8.1...",
    "os":"...",
    "ports":{"proxy":11211,"direct":11210}
  },{
```
What is missing is the [Node.CouchAPIBase](http://docs.couchbase.com/sdk-api/couchbase-net-client-2.0.1/html/DD51ADF3.htm) property (according to the link, added in 2.0.1.0).

If that property is not set, then in `routeconfig.go` we skip over this `if` statement:
```go
 			if node.CouchAPIBase != "" {
 				// Slice off the UUID as Go's HTTP client cannot handle being passed URL-Encoded path values.
 				capiEp := strings.SplitN(node.CouchAPIBase, "%2B", 2)[0]
 
 				capiEpList = append(capiEpList, capiEp)
  			}
```
This results in an invalid configuration, as the `capiEpList` is then empty.
```go
func (config *routeConfig) IsValid() bool {
	if len(config.kvServerList) == 0 || len(config.mgmtEpList) == 0 {
		return false
	}
	switch config.bktType {
	case BktTypeCouchbase:
		return len(config.vbMap) > 0 && len(config.vbMap[0]) > 0 && len(config.capiEpList) > 0
	case BktTypeMemcached:
		return len(config.ketamaMap) > 0
	default:
		return false
	}
}
```
The `case BktTypeCouchbase:` statement in particular is where our issue crops up.

The property is not present, so we do not append any servers to `config.capiEpList`.

The workaround is to simply append servers to the `capiEpList` if they are present (accomplished by the patch).  This code will append the servers to the `capiEpList` only if the length of the `capiEpList` is `0` (meaning it has not been populated).

This has been tested against our production 1.8.1 cluster and results in a valid configuration.

@StabbyCutyou @csmith0651

### CODE REVIEW

**Comment by csmith0651** [comment]
looks reasonable, but I don't know enough about couchbase.

**Comment by StabbyCutyou** [comment]
Same reply as craig

**Comment by StabbyCutyou** [comment]
Explanation helps add a lot of needed context - thanks Dean!

Any chance we can contribute this back upstream?

**Comment by deanxorr** [comment]
Closing this one in favor of https://github.com/Tapjoy/gocb/pull/2, which includes some needed namespace changes for the fork

**Pull request closed without merging**
